services:
  mongodb:
    image: mongo:latest
    container_name: aprisio
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: aprisioUser
      MONGO_INITDB_ROOT_PASSWORD: superStrongAprisopasSWord--231
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
